version: "3.7"

services:
  web:
    build:
      target: dev
      args:
        PYTHON_IMAGE_TAG: 3.8
    env_file: ./envs/local/web.env
    volumes:
      - ".:/app"
    ports:
      - "8000:8000"

  db:
    env_file: ./envs/local/db.env
